### ISSUE TITLE
Composer require not working

### ISSUE THREAD

**Issue by mentiondev** [simplygoodwork/donkeytail-plugin#13]
Running `composer require simplygoodwork/craft-donkeytail` doesn't work. So can't install the plugin?

**Comment by chrisrowe** [comment]
Hey @mentiondev thats correct, it's not yet on packagist. We'll let you know when it's launched and good to install.

**Comment by wallacio** [comment]
What are the likely timescales for this appearing on packagist? I've added it composer by repository but it'd be great to be able to require it 'properly'.

**Comment by chrisrowe** [comment]
Real soon, we're just ironing out some last minute details so expect it in the coming days
