### ISSUE TITLE
Canvas source location asset path

### ISSUE THREAD

**Issue by wallacio** [simplygoodwork/donkeytail-plugin#15]
This is a great plugin, can't wait to see it fully released for Craft 3.

Is it possible to have similar functionality that Assets have which is to specify the path and ideally, restrict to an upload path? We have a very structured assets volume with many folders, to make sense of the thousands of assets stored in it. If it's possible to specify an upload location for the source canvas, that would allow it to live somewhere other than the volume root.

**Comment by robinsm** [comment]
Being able to select a canvas source is now part of the Donkeytail plugin.

<img width="1427" alt="Screenshot_2021-10-12_at_15_52_02" src="https://user-images.githubusercontent.com/4096355/136969262-80e15346-a447-474d-bcf9-a1f303f185f7.png">
