### ISSUE TITLE
Allow multiple Donkeytail fields per entry - feature request

### ISSUE THREAD

**Issue by wallacio** [simplygoodwork/donkeytail-plugin#16]
Similar to how multiple asset/entry fields can be attached to an entry, it would be great to allow multiple Donkeytail canvases + markers per entry. I've got a good, if top secret use case.

**Comment by chasegiunta** [comment]
@wallacio This should be possible. Are you getting a javascript error upon having two donkeytail fields on an entry type?

**Comment by wallacio** [comment]
Not multiple fields, rather a single field with multiple related DonkeyTail items (like is possible with Assets or Entries). I now realise that's probably a bit dumb and I could most likely achieve it by repeating a Matrix block that contains a Donkeytail field instead.

**Comment by chasegiunta** [comment]
@wallacio Ah yeah. I think that's probably outside the scope of the plugin for now, but I'll leave this open in case others flag it as a need for future versions

**Comment by wallacio** [comment]
Closing this as a pointless feature request by me going for the keyboard before thinking it through. 
Required result by using a Matrix block which contains a Donkeytail field.
