### ISSUE TITLE
[Bug] - Call to undefined method craft\helpers\Html::id()

### ISSUE THREAD

**Issue by belkin** [simplygoodwork/donkeytail-plugin#17]
Hi there,
After installing the plugin on Craft CMS 3.4.30 with Super Table plugin I'm getting the following error when I try to edit SuperTable field or create one: 
`Call to undefined method craft\helpers\Html::id()`

**Comment by chasegiunta** [comment]
Hey @belkin... I'll take a look at a this...

FYI, before this gets officially released, the minimum Craft version may bump up to 3.5.6+

**Comment by chasegiunta** [comment]
@belkin Are you still experiencing this on 3.5+ by chance? Also, what version of Super Table are you on?

**Comment by chasegiunta** [comment]
Closing for now
