### ISSUE TITLE
Donkeytail is not listed in Craft Plugin Store

### ISSUE THREAD

**Issue by ryanmasuga** [simplygoodwork/donkeytail-plugin#18]
Perhaps you don't want it listed, but it is in a public repo with clear instructions on how to install it. Is there any support offered whatsoever if we were to install this and use it instead of a similar plug-in that is in the Craft Plugin Store that's commercial?

**Comment by garrettwinder** [comment]
We're in the process of getting everything together to put Donkeytail in the plugin store and a few non-code related things have held things up. So yes, it's just here right now looking like it's a thing but it isn't yet. For now if you use it you'll get the "free support", so if that is an issue than I'd just buy the similar plugin you're referring to.

**Comment by ryanmasuga** [comment]
Thanks for clarifying, @garrettwinder .
