### ISSUE TITLE
Template error when accessing field with zero pins

### ISSUE THREAD

**Issue by simple-nicholas** [simplygoodwork/donkeytail-plugin#20]
Hey, I get the following error when trying to access the pins (ie to check if there are any) on a field with zero pins saved:

![screenshot](https://user-images.githubusercontent.com/50125070/99602387-4697c080-2a51-11eb-8fc0-d1e89696cc58.png)

The following changes to `src/models/DonkeytailModel.php` worked for me:

```php
public function getPinsElementType() {
    if (!is_array($this->pinIds) || !count($this->pinIds)) {    // the is_array test
        return null;
    }
    return (new Elements)->getElementTypeById($this->pinIds[0]);
}

public function getPins() {
    $elementTypeClass = $this->getPinsElementType();
    if($elementTypeClass == null) {    // and this if statement
        return [];
    }
    	
    $query = $elementTypeClass::find();
    $criteria = [
```

**Comment by garrettwinder** [comment]
Thanks, @simple-nicholas

**Comment by chasegiunta** [comment]
Not asking for your money on this, unless you want big feature stuff soon, but figured you would be holding off on big feature stuff.

If you wanna figure out version milestones on it though, holla 

Not gonna do freelance client stuff unless it’s minor, then I’ll take your money 💙

**Comment by chasegiunta** [comment]
@simple-nicholas Cut a new release with this fix. Thanks for reporting!
