### ISSUE TITLE
Missing closing div

### ISSUE THREAD

**Issue by wallacio** [simplygoodwork/donkeytail-plugin#21]
I think there's a missing closing `</div>` somewhere in the back-end templates. I've had a trawl through the generated code but can't see anything obvious. 

I've got two examples of it happening; editing a simple Donkeytail field, or where there's a Donkeytail field in a Matrix block. Whenever this field is present, you'll notice that the generated HTML is incomplete (highlighted by View Source in Firefox). 

![image](https://user-images.githubusercontent.com/7721989/101349373-2c4d4780-3885-11eb-8e63-bc4ba2e0b11a.png)

I'm also unable to edit a matrix field that contains a Donkeytail block, which may be connected with this but I can raise that separately if fixing the output HTML doesn't resolve it.

**Comment by wallacio** [comment]
Ok - I think your closing div is missing from templates/_components/fields/Donkeytail_settings.twig. I'd create a PR but better if you check that's where it's supposed to be.

**Comment by chasegiunta** [comment]
@wallacio Wow, yep. Not sure how we've missed this one. Feel free to PR, otherwise I can push a fix tomorrow.

**Comment by chasegiunta** [comment]
@wallacio pushed an update for this. Check if this solves your Matrix issue and report back.

**Comment by wallacio** [comment]
Looks good to me @chasegiunta - thanks!
