### ISSUE TITLE
Pins element type of entry in multi-site

### ISSUE THREAD

**Issue by wallacio** [simplygoodwork/donkeytail-plugin#22]
I don't know if this is an omission, or something I've not configured correctly.

It would appear that when using 'Entries' element type for pins, it would appear that it's only allowing selection of Entries from the primary site, with no option to select an entry from the current site being edited. 

Can you confirm if this is a limitation or something I've cocked up in config?

**Comment by chasegiunta** [comment]
@wallacio Entries don't exist exclusively in one Site vs another. If you have all sites configured in the Section of the Entries you're trying to select, you'll see the entry. Look at the section of the entries you're trying to find and ensure you have that section enabled for all Sites.

**Comment by wallacio** [comment]
@chasegiunta No, that's not correct. Our product would fundamentally not work if this was the case - it's perfectly possible to create entries on a per-site basis, if so configured:

![image](https://user-images.githubusercontent.com/7721989/103521942-8552d000-4e71-11eb-9f19-c1b88f020b46.png)

Even if it was the case for a multi-site installation, you'd still want to be able to associate a pin with the entry in a specific site. Otherwise, what's the point in multi-site?

**Comment by chasegiunta** [comment]
Hmmm, sorry then I'll take a look! I must be getting confused with Craft 2's old way of doing translations, where an _entry_ was an element with multiple translations. I haven't worked with Sites in a different way thus far. An entry element would have the same ID in each site, the way I've worked with them in the past. I'll keep you posted!
