### ISSUE TITLE
Pin type custom

### ISSUE THREAD

**Issue by akukral** [simplygoodwork/donkeytail-plugin#23]
Is there a way to set the plugin up so so the pin type is only just a plain text field not linked to entry, assets, categories or existing structures?

**Comment by garrettwinder** [comment]
There's currently not. We've had this request a couple of times though so is something we may consider, but not in the short term.

**Comment by akukral** [comment]
Okay, thanks. Appreciate the quick reply!

**Comment by robinsm** [comment]
To use just a plain text field, you can create a new section channel that contains just the default 'Title' field.  Please see the attached video.


https://user-images.githubusercontent.com/4096355/136967734-8fca532b-ceb9-49cd-b99c-5b0e44d75ece.mp4
