### ISSUE TITLE
A way to control the order of the pins?

### ISSUE THREAD

**Issue by msmith7904** [simplygoodwork/donkeytail-plugin#27]
Hi, great plugin, it's perfect for a feature that I'm working on for a client.  The FE implementation has a list of cards next to a map with corresponding pins.  The client is asking why the order of the cards (and tab order of the pins) is not the same as the order of the pins in the control panel.  Is there a way to output the pins in a specific order, rather than just pin.element.postDate?  Especially since they're draggable in the control panel, seems like that would/should have some effect.

**Comment by garrettwinder** [comment]
@msmith7904 Howdy -- the order is supposed to be set by the arrangement of elements (pins!) selected in the Admin UI. And you can drag and drop these into any order you'd like.

Are you having different results? Thanks!

**Comment by msmith7904** [comment]
@garrettwinder I am definitely seeing different results.
For example, this demo code always has the latest pin.element at the top, regardless of the pin order in the Admin UI. 
```
{% for pin in {block}.{donkeytailField}.pins %}
    <pre>{{ dump(pin.element.title) }}</pre>
    <pre>{{ dump(pin.element.postDate|time('y m d')) }}</pre>
{% endfor %}
```
