### ISSUE TITLE
Canvas not appearing

### ISSUE THREAD

**Issue by pl-mnm** [simplygoodwork/donkeytail-plugin#31]
Hi, for some reason the canvas doesn't appear after I've loaded an image and selected some pins, and I'm getting console errors:

<img width="650" alt="Screenshot 2022-01-31 at 11 03 32 AM" src="https://user-images.githubusercontent.com/3905170/151737776-391be8ec-6323-4841-b86e-1593999fea13.png">

I tried in FF97 and Chrome 97 and in Craft 3.7.25.1 as well as 3.7.30.1.

Any idea what can be causing this?

Thanks in advance.

**Comment by chrisrowe** [comment]
Hey @pl-mnm, can you confirm the asset hasn't been deleted at the source?

**Comment by Braufoilt** [comment]
Hi, I have the same problem as shown and can confirm the asset hasn't been deleted
![Screenshot 2022-04-29 at 13 26 46](https://user-images.githubusercontent.com/6859955/165935955-7d6bc0bd-3c33-4ff9-ad57-4e8b097c390e.png)
.

**Comment by andrewmenich** [comment]
Hi @pl-mnm @Braufoilt sorry for the radio silence. I wasn't able to reproduce this locally, but I believe I've identified the issue and pushed some changes for the next release that should resolve this for you. You can try it out now by updating your composer.json to `"simplygoodwork/craft-donkeytail": "dev-craft-3-develop as 2.0.6"` and running `composer update`

**Comment by andrewmenich** [comment]
This should be fixed in v3.0.0. Please let us know if the issue persists!

**Comment by andrewmenich** [comment]
Hey folks, sorry for the potential confusion here. This was mistakenly closed as being resolved in v3.0.0, but that is the Craft 4 compatible version of Donkeytail. 

The Craft 3 compatible fix for this issue was just tagged in 2.0.7. Please let us know if anything else crops up.
