### ISSUE TITLE
Craft 4 Support

### ISSUE THREAD

**Issue by robmcfadden** [simplygoodwork/donkeytail-plugin#33]
I'm considering using this for a feature on an upcoming build using Craft 4. Any thoughts on when (and if) this plugin will have Craft 4 compatibility? Thanks!

**Comment by chrisrowe** [comment]
Hey Rob, it's definitely on our road map but we can't commit to a release date just yet. We'll update this issue as we know more but just to give you a ball park I think we're hoping for somewhere in the "next few months" range.

**Comment by robmcfadden** [comment]
Thanks for the quick response!

**Comment by braedenfoster** [comment]
I am actively using this plugin as it is useful for showing store locations on a custom map for a client. It's good to know it's on the cards for an upgrade sometime in the near future. Thank you for a great plugin!

**Comment by andrewmenich** [comment]
Hey folks, we just released [v3.0.0-beta.1](https://github.com/simplygoodwork/craft-donkeytail/tree/craft-4) for Craft 4! For active Craft 3 installs, you will now see Donkeytail listed as "Ready" in the Craft 4 Upgrade utility screen. 

If you're running a Craft 4 site, you can try the plugin by adding `"simplygoodwork/craft-donkeytail": "^3.0.0-beta.1"` to your composer.json. 

Please let us know if you encounter any issues with the new version!
