### ISSUE TITLE
Craft 4: Pins No Longer Loading

### ISSUE THREAD

**Issue by brettburwell** [simplygoodwork/donkeytail-plugin#36]
Hi y'all. I was excited to see the Craft 4 release a few days ago. Congrats on getting that out the door. 

Testing just now I'm having an issue where pins from previously created entries aren't loading when viewing my Donkeytail fields in the control panel. It's worth noting that this is happening in a Donkeytail field within a Matrix block. 

Everything seems to work correctly when I create a new Matrix field (I'm able to select a canvas and then select entries to pin onto the canvas). I can save the entry and see everything output correctly on the front end. 

But when I reload the entry in the control panel (or view any entries I previously created before upgrading) the pins no longer load onto the canvas. Here's an image for reference. 

![donkey-tail-no-pins](https://user-images.githubusercontent.com/1228671/187509861-95d701a2-579a-42c9-ac90-3a82cf9e6e5a.png)

**System Specs**
- Craft 4.2.3
- PHP 8.0.21
- MySQL 10.3.35
- Donkeytail 3.0.0

There aren't any obvious errors in the dev tools console or Craft logs that I'm seeing. If there's any other info I can pass along that'd be helpful please let me know.

**Comment by andrewmenich** [comment]
Hey @brettburwell thanks for reporting this issue. I will look into it now!

**Comment by brettburwell** [comment]
Awesome. Thanks @andrewmenich.

**Comment by andrewmenich** [comment]
@brettburwell I believe I've identified the issue. You can test the fix out locally by adding `"simplygoodwork/craft-donkeytail": "dev-craft-4-develop as 3.0.0"` to your composer.json. I'll cut a new release here shortly, unless you find this hasn't resolved the issue!

**Comment by brettburwell** [comment]
@andrewmenich That looks like it did the trick. Thanks for the quick fix! Much appreciated.

**Comment by brettburwell** [comment]
One other small thing. Maybe I'm misremembering, but previously when you clicked on an entry in the "Pins" column it would auto-select the corresponding pin on the canvas. That doesn't appear to be working any longer. 

If you'd prefer I open another GitHub issue (or if I'm making up features that don't exist) let me know!

**Comment by andrewmenich** [comment]
Resolved in v3.0.1. Thanks again for the report.

Also, I don't believe it did, but it does now 🙂

**Comment by brettburwell** [comment]
Amazing! Thanks again @andrewmenich.
