### ISSUE TITLE
Upgrading from Craft 2 to craft 4 - exceptions

### ISSUE THREAD

**Issue by rowansentesy** [simplygoodwork/donkeytail-plugin#42]
Hello!

I'm working on a client site and they have Donkey Tail v1.0.5 installed on Craft 2 presently.

I am working through all plugin issues and on Craft 4.4.2 with Donkey Tail version 3.0.1, i'm getting issues on the front-end and also when editing entries with a Donkeytail field. 

Editing entry issue:
https://gyazo.com/364c03f8bbdaef0110f23e2d48747ef4

The field is called basementIllustration.

On the front end, the I tried to edit the template to use the `pin.style` property but get an error..

When I just dump the pin, I do get some data related to the field
```
{% for pin in craft.entries.section('problems') %}
{{ dump(pin) }}
{% endfor %}
```
However, the format looks incorrect, and I can't output the actual data `pin.basementIllustration`
https://gyazo.com/5aab1dc085b57ded8008da80cac1d023

I'm assuming there have been changes since Donkeytail v1x and there is a step needed, but I have found zero documentation indicating how to migrate through Craft v3x.

Can you advise?

thanks,
Rowan

**Comment by rowansentesy** [comment]
I just tried to intervene on Craft 3 during the upgrade by installing 2.0.7
`composer require simplygoodwork/craft-donkeytail:2.0.7` 
When the site was loaded, I found the identical issue when trying to edit an entry with the donkeytail field loaded. 

> Setting unknown property: simplygoodwork\donkeytail\models\DonkeytailModel::leftPercentage

Do i need to rebuild the pins using on Craft 3/4? 

Thanks,
Rowan

**Comment by andrewmenich** [comment]
Hi Rowan, sorry for the late reply! Is there any chance you could send a copy of your Craft 2 database to dev@simplygoodwork.com? I'm thinking we'll need to put together a migration for the Craft 2 -> 3 update. Thanks!

**Comment by chrisrowe** [comment]
I'm closing this one out since it's stale. @rowansentesy Please reopen if you need anything else.
