### ISSUE TITLE
Cannot get the canvas image using Element API

### ISSUE THREAD

**Issue by clintonbeattie** [simplygoodwork/donkeytail-plugin#45]
When trying to access the image using this code within the 'transformer' it returns error message stating...

"message": "Calling unknown method: simplygoodwork\\donkeytail\\models\\DonkeytailModel::one()"

`// Get the URL of the inspiration image from Donkeytail field
                    $donkeytailField = 'collectionInspirationImage'; // Replace this with the actual handle of your Donkeytail field

                    try {
                        $inspirationImageUrl = $entry->$donkeytailField->one()->canvas->url;
                    } catch (\Throwable $e) {
                        // Log the error in the Craft log
                        Craft::error("Error accessing Donkeytail field: " . $e->getMessage(), __METHOD__);

                        // Set a default value for inspirationImageUrl in case of error
                        $inspirationImageUrl = '';

                        // In devMode, return the error message in the JSON response
                        if (Craft::$app->config->getGeneral()->devMode) {
                            return [
                                'error' => [
                                    'code' => $e->getCode(),
                                    'message' => $e->getMessage(),
                                ],
                            ];
                        }
                    }

                    // Restore the original devMode value
                    Craft::$app->config->getGeneral()->devMode = $devMode;`

**Comment by chrisrowe** [comment]
@clintonbeattie You got this sorted?

**Comment by clintonbeattie** [comment]
I did indeed. Thank you for replying to check.
