### ISSUE TITLE
Marker point slightly off

### ISSUE THREAD

**Issue by johnwbaxter** [simplygoodwork/donkeytail-plugin#47]
Hi,

The marker points are being output slightly off from where they should be.

Everything is as instructed but when trying to debug I read the docs and saw this about negative margins and wondered what I've missed in not understanding how to define/specify what negative margins to use?

![image](https://github.com/simplygoodwork/craft-donkeytail/assets/338729/df028dd3-0458-40a5-834f-38f61773cf81)

I have my element inside a relative positioned div with the image inside and my markers like this:

```
<div class="relative">
  <img src="{{ block.map.canvas.url }}" alt="Map" class="w-full">
      {% for pin in block.map.pins %}
          <div class="absolute" style="{{ pin.style }}">
              Blah blah blah
          </div>
      {% endfor %}
</div>
```

**Comment by chrisrowe** [comment]
Hey @johnwbaxter,

This negative offset just applies to the fact a marker icons anchor my not be central to the image. If your marker icon is 10px wide and 20px tall, if you absolutely positioned it with `donkeytailField.style` that would place the icon on the bottom right you'd need it -5px left and -20px up to make the point of the icon match the exact position of the pin.

**Comment by johnwbaxter** [comment]
@chrisrowe Ahhhhhhhh. Sorry, my brain had quite clearly not considered that element! Cheers Chris!

**Comment by chrisrowe** [comment]
No worries - it is Monday after all!
