### ISSUE TITLE
Craft 3?

### ISSUE THREAD

**Issue by richstandbrook** [simplygoodwork/donkeytail-plugin#5]
Are they any plans for a Craft 3 version soon?

**Comment by chrisrowe** [comment]
Hey Rich, we absolutely have plans to port this to Craft 3, it'll be the "Pro" version with some more features and improved functionality.

Donkeytail is just a side project for now though so we have no solid timelines I'm afraid.

**Comment by richstandbrook** [comment]
Cool 👍 I'll keep an eye on it and try and come up with something else in the meantime.
