### ISSUE TITLE
Undefined index blocking entry access in CP

### ISSUE THREAD

**Issue by Emkaytoo** [simplygoodwork/donkeytail-plugin#6]
We had an existing channel for locations on a US map, with entries populated into the channel. When we added the donkeytail field to the entryType, we were able to go into the entries and set the points.

After about 6 entries were created, we got an error: `Internal Server Error, Undefined index: topPercentage`. I'm now unable to open any of the entries with that field in the entryType, regardless of whether or not the point was set.

Where should I begin looking to resolve this?

**Comment by chrisrowe** [comment]
Thanks for reporting @Emkaytoo I've just pushed a bugfix release 1.0.4 for this.
