### ISSUE TITLE
Craft 3 Support

### ISSUE THREAD

**Issue by artmem** [simplygoodwork/donkeytail-plugin#7]
Will this plugin be ported to Craft 3? I'm about to build a site where this would help tremendously, but it's going to be a Craft 3 site.

**Comment by chrisrowe** [comment]
@artmem Hey there, we have no immediate plans to port this to Craft 3 although it is on our roadmap. The native focal point support should get you some of the way toward similar functionality though.

**Comment by j-greig** [comment]
Would love to see a C3 version of this fine plugin :)
