### ISSUE TITLE
Craft indicating update, plugin file at v1.0.3 instead of v1.0.4

### ISSUE THREAD

**Issue by justinholtweb** [simplygoodwork/donkeytail-plugin#8]
Craft keeps nagging me about a plugin update for Donkeytail, indicating the 1.0.4 release is out there but the class still returns v1.0.3 as the current version from getVersion(), therefore when updating the plugin Craft doesn't think you have actually updated it.

**Comment by chrisrowe** [comment]
@justinholtweb Hey Justin, thanks for flagging this. I've revved the version again and fixed the returned version number too.

Cheers!

**Comment by justinholtweb** [comment]
Thats the fastest resolution I've ever experienced! Thanks Chris!
